In [5]:
from pandas_datareader import data
import datetime
from bokeh.plotting import figure, show, output_file

start = datetime.datetime(2020,6,1)
end = datetime.datetime(2020,6,10)
df  = data.DataReader(name="AAPL",data_source="yahoo",start=start,end=end)
df

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2020-06-01,322.350006,317.209991,317.750000,321.850006,20197800,321.850006
2020-06-02,323.440002,318.929993,320.750000,323.339996,21910700,323.339996
2020-06-03,326.200012,322.299988,324.660004,325.119995,26122800,325.119995
2020-06-04,325.619995,320.779999,324.390015,322.320007,21890100,322.320007
2020-06-05,331.750000,323.230011,323.350006,331.500000,34312600,331.500000
2020-06-08,333.600006,327.320007,330.250000,333.459991,23913600,333.459991
2020-06-09,345.609985,332.010010,332.140015,343.989990,36928100,343.989990
2020-06-10,354.769989,346.089996,347.899994,352.839996,41662900,352.839996

In [18]:
def increase_decrease(close, opn):
    if close > opn:
        value = "Increase"
    elif close < opn:
        value = "Decrease"
    else:
        value = "Equal"
    return value

df["Status"] = [increase_decrease(close, opn) for close, opn in zip(df.Close,df.Open)]
df

,High,Low,Open,Close,Volume,Adj Close,Status
Date,,,,,,,
2020-06-01,322.350006,317.209991,317.750000,321.850006,20197800,321.850006,Increase
2020-06-02,323.440002,318.929993,320.750000,323.339996,21910700,323.339996,Increase
2020-06-03,326.200012,322.299988,324.660004,325.119995,26122800,325.119995,Increase
2020-06-04,325.619995,320.779999,324.390015,322.320007,21890100,322.320007,Decrease
2020-06-05,331.750000,323.230011,323.350006,331.500000,34312600,331.500000,Increase
2020-06-08,333.600006,327.320007,330.250000,333.459991,23913600,333.459991,Increase
2020-06-09,345.609985,332.010010,332.140015,343.989990,36928100,343.989990,Increase
2020-06-10,354.769989,346.089996,347.899994,352.839996,41662900,352.839996,Increase

In [9]:
p = figure(x_axis_type='datetime',width=1000,height=300)
p.title.text="Candlestick Chart"

hours_12 = 12 * 60 * 60 * 1000

p.rect(df.index[df.Status = "Increase"], (df.Open + df.Close)/2, hours_12,
       abs(df.Open - df.Close), fill_color="green", line_color="black")

p.rect(df.index[df.Status = "Decrease"], (df.Open + df.Close)/2, hours_12,
       abs(df.Open - df.Close), fill_color="red", line_color="black")

output_file("CandleStick.html")
show(p)

BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('x', 7), ('y', 8)
BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('height', 8), ('x', 7), ('y', 8)
BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('x', 1), ('y', 8)
BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('height', 8), ('x', 1), ('y', 8)